### ISSUE TITLE
Intercross - 20 - Create activity to import list of lines and replace barcode ID with human readable name

### ISSUE THREAD

**Issue by trife** [trife/Hackathon#40]
Augment list of   current crosses to include desired crosses with count 0
--

**Comment by bauchetg** [comment]
Very likely, breeders would request to display additional stockprops  on the cross label. :
-pedigree string
-ploidy
This may require metadata to be imported to intercross ( possibly through the field design template as it is done in Fieldbook)

**Comment by chaneylc** [comment]
Users can now import a csv of ids, names which will replace all view-able occurrences of cross ids with their respective names. Readable names save across app loads.
