### ISSUE TITLE
Intercross - 15 - Incorporate ability to print a label including barcode, cross id, and date via Zebra printer

### ISSUE THREAD

**Issue by trife** [trife/Hackathon#43]

**Comment by bellerbrock** [comment]
The way I implemented barcode printing in fieldbook earlier in the spring is . . . ugly. A better solution that could also be used in intercross would be to refactor the code into a separate zebra printing library.

Apps that want to use it could then add it as a dependency and supply it with the necessary text values. The library will then handle the install message, dialog for picking label size and layout, dynamic sizing based on text length, zpl creation, and communication with the zebra sdk internally. 

Or at least that's the rough plan. Looking through docs at  https://developer.android.com/studio/projects/android-library now to learn more.

**Comment by chaneylc** [comment]
I used the Zebra SDK to internally print barcodes from Intercross.

commit
a95bd745249b49ffe9bbede6a136332ed8d2629b
