### ISSUE TITLE
OneKK - 15 - Add sample images accessible via navigation drawer

### ISSUE THREAD

**Issue by trife** [trife/Hackathon#44]

**Comment by disssid** [comment]
Navigation drawer opens to a list of the samples in a dialog
Selecting a sample opens a dialog that previews the image (similar to the post analysis preview) with options at the bottom to 'Close' or 'Analyze'
Selecting 'Analyze' will run the image through the currently selected analysis pipeline

https://github.com/PhenoApps/OneKK/commit/f552adb96acd40b9ff48b2911cb54c1437dede25

**Comment by disssid** [comment]
When using sample images of resolution 2857 x 4160 on Nexus 5, the images are not rendered on the TouchImageView with the following message,

`W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2857x4160, max=4096x4096)`

Reduced the resolution down to 2857 x 4000 and the samples are rendered.
