### ISSUE TITLE
Intercross- add cross property file with the same format as trait file

### ISSUE THREAD

**Issue by titima15** [trife/Hackathon#55]

**Comment by titima15** [comment]
Include constrain for each cross property.

**Comment by nickmorales** [comment]
cross properties that we know about:

## Cross properties for cassavabase
Tag Number,Pollination Date,Number of Bags,Number of Flowers,Number of Fruits,Number of Seeds

## Cross properties for yambase
Number of Flowers,Pollination Date,Harvest Date,Number of Seeds Harvested,Days to Maturity,Seed Extraction Date,Number of Seeds Extracted,Number of Viable Seeds,Number of Nonviable Seeds, Days from Harvest to Extraction

## Cross properties for musabase
First Pollination Date,Repeat Pollination Date,Harvest Date,Seed Extraction Date,Number of Seeds Extracted,Embryo Rescue Good Seeds,Embryo Rescue Bad Seeds,Embryo Rescue Total Seeds,Embryo Rescue Date,Subculture Date,Subcultures Count,Subcultures Multiplication Number,Rooting Date,Rooting Plantlet,Germinating After 2 Weeks Date,Active Germinating After 2 Weeks,Germinating Afte 8 Weeks Date,Active Germinating After 8 Weeks,Screenhouse Transfer Date,Hardening Date
